image: docker:24.0.5

services:
  - docker:24.0.5-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build_and_push

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

build_and_push_image:
  stage: build_and_push
  script:
    # Version aus Dockerfile extrahieren
    - export OBSIDIAN_VERSION=$(grep -E '^ARG OBSIDIAN_VERSION=' Dockerfile | cut -d= -f2)
    - echo "Using OBSIDIAN_VERSION=$OBSIDIAN_VERSION"

    # Image bauen
    - docker build --build-arg OBSIDIAN_VERSION=$OBSIDIAN_VERSION -t $CI_REGISTRY_IMAGE:$OBSIDIAN_VERSION .
    - echo "Container build!"
    # Weitere Tags setzen
    - docker tag $CI_REGISTRY_IMAGE:$OBSIDIAN_VERSION $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$OBSIDIAN_VERSION $CI_REGISTRY_IMAGE:latest
    - echo "Tags set."

    # Pushen
    - docker push $CI_REGISTRY_IMAGE:$OBSIDIAN_VERSION
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "Container pushed to registry."
